name: CI

on: [push, pull_request]

jobs:


  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-18.04]

    steps:

    - uses: actions/checkout@v2

    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
        PKG_CONFIG: '/usr/local/bin/pkg-config'
        PKG_CONFIG_PATH: '/usr/local/lib/pkgconfig/'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check python version
      run: python -c "import sys; import platform; print('Python %s implementation %s on %s' % (sys.version, platform.python_implementation(), sys.platform))"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.python-version }}-pythonpip

    - name: Install coin
      run: |
        sudo apt-get update
        sudo apt-get install coinor-cbc
        dpkg -L coinor-cbc
        sudo apt-get install coin-or-libcbc-dev
        dpkg -L coin-or-libcbc-dev

    - name: Install dependencies
      run: |
        python -m pip install numpy scipy
        python -m pip install cylp

    - name: Install current package
      run: python -m pip install .

    - name: list installed packages
      run: python -m pip list

    - name: run tests
      run: |
        python -m pytest . --verbose --color=yes
